name: 'load.test'

on: #Allow plan to run on PR
  pull_request:
      paths:
        - '**'
  push:
    branches:
      - 'main'
  workflow_dispatch:
   inputs:
    enableManualDeployement :
      description: 'Click to enable manual deployment from a non master branch to the test environment.'
      default: false
      required: true
      type: boolean
jobs:
  load_test:
    name: k6 Load Test
    runs-on: ubuntu-latest
   
    steps:

    - name: Checkout
      uses: actions/checkout@v3
      
    - name: Run local k6 test
      uses: grafana/k6-action@v0.2.0
      with:
        filename: test.js
   
   